### ISSUE TITLE
Service init failed: Migration failed err: unable to open database file

### ISSUE THREAD

**Issue by chenjiabin** [liqiang311/zabbix-grafana#1]
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Starting Grafana" logger=server version=5.4.3 commit=6539180 branch=HEAD compiled=2019-01-14T22:26:26+0800
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="App mode production" logger=settings
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Initializing HTTPServer" logger=server
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Initializing SqlStore" logger=server
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
grafana    | t=2019-02-13T13:58:40+0800 lvl=info msg="Starting DB migration" logger=migrator
grafana    | t=2019-02-13T13:58:40+0800 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: unable to open database file"

**Comment by liqiang311** [comment]
@chenjiabin 已修复，是因为我想把grafana的db文件放在外面（便于恢复）导致的，参考我的blog https://blog.csdn.net/QiangLi_strong/article/details/81021836 重新pull下代码。

**Comment by liqiang311** [comment]
@chenjiabin 先docker-compose down掉所有容器，然后删除目录，重新git clone.

**Comment by kenttanl** [comment]
Try `sudo chown -R 472:472 /var/lib/grafana` in your server (/var/lib/grafana is host volume). 472 is grafana USER ID (>= v5.1), detail: https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v5-1-or-later
